/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pm;

import java.awt.EventQueue;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author HITAM-PC
 */
public class Ambil_Minyak extends javax.swing.JFrame {
    Connection con;
    Statement stat, stat2, stat3, stat4;
    ResultSet rs;
    String sql;
    ArrayList nama_nelayan = new ArrayList();
    /**
     * Creates new form home
     */
    public Ambil_Minyak() {
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        stat2 = DB.stm;
        stat3 = DB.stm;
        stat4 = DB.stm;
        loadnama();
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JLabel();
        textNama = new javax.swing.JTextField();
        textJumlahMinyak = new javax.swing.JTextField();
        CBtanggal = new javax.swing.JComboBox();
        submit = new javax.swing.JButton();
        CBbulan = new javax.swing.JComboBox<String>();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frame1"); // NOI18N
        setPreferredSize(new java.awt.Dimension(680, 566));
        setResizable(false);
        setSize(new java.awt.Dimension(680, 566));
        getContentPane().setLayout(null);

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/icon/back.png"))); // NOI18N
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backButtonMouseReleased(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(40, 20, 80, 40);

        textNama.setBackground(new java.awt.Color(25, 115, 148));
        textNama.setFont(new java.awt.Font("Roboto Slab ExtraBold", 0, 14)); // NOI18N
        textNama.setForeground(new java.awt.Color(255, 255, 255));
        textNama.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textNama.setToolTipText("");
        textNama.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        textNama.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        textNama.setSelectionColor(new java.awt.Color(255, 255, 255));
        textNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNamaActionPerformed(evt);
            }
        });
        textNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textNamaKeyPressed(evt);
            }
        });
        getContentPane().add(textNama);
        textNama.setBounds(240, 190, 180, 40);

        textJumlahMinyak.setBackground(new java.awt.Color(25, 115, 148));
        textJumlahMinyak.setFont(new java.awt.Font("Roboto Slab ExtraBold", 0, 14)); // NOI18N
        textJumlahMinyak.setForeground(new java.awt.Color(255, 255, 255));
        textJumlahMinyak.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textJumlahMinyak.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        textJumlahMinyak.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        textJumlahMinyak.setSelectionColor(new java.awt.Color(255, 255, 255));
        textJumlahMinyak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textJumlahMinyakActionPerformed(evt);
            }
        });
        getContentPane().add(textJumlahMinyak);
        textJumlahMinyak.setBounds(240, 240, 180, 40);

        CBtanggal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Tanggal-", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        CBtanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBtanggalActionPerformed(evt);
            }
        });
        getContentPane().add(CBtanggal);
        CBtanggal.setBounds(240, 300, 90, 20);

        submit.setText("Submit");
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
        });
        getContentPane().add(submit);
        submit.setBounds(320, 370, 90, 30);

        CBbulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Bulan -", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        CBbulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBbulanActionPerformed(evt);
            }
        });
        getContentPane().add(CBbulan);
        CBbulan.setBounds(340, 300, 80, 20);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/images/ambil_minyak.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(4, 4, 670, 560);

        setSize(new java.awt.Dimension(696, 605));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textJumlahMinyakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textJumlahMinyakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textJumlahMinyakActionPerformed

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        String nama = textNama.getText();
        String jumlah_minyak = textJumlahMinyak.getText();
        
        SimpleDateFormat sdf = new SimpleDateFormat();
        int numbers_to_add_max = 31;
        for (int i = 1; i <= numbers_to_add_max; i++) {
            CBtanggal.addItem(new Integer(i));
        }
        int year = Calendar.getInstance().get(Calendar.YEAR);
        
        String tanggal = CBtanggal.getSelectedItem().toString();
        String bulan = CBbulan.getSelectedItem().toString();
        String dmy = year+"-"+bulan+"-"+tanggal;
        check();
        try{
           if(nama.isEmpty() || jumlah_minyak.isEmpty() || tanggal.isEmpty() || bulan.isEmpty()){
               JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!!!");
           }else{
                String insert_minyak = "INSERT INTO ambil_minyak (nama_nelayan, tanggal, jumlah) "
                + "VALUES ('"+nama+"','"+String.valueOf(dmy)+"','"+jumlah_minyak+"')";
                stat4.executeUpdate(insert_minyak); 
                JOptionPane.showMessageDialog(null, "Data Berhasil ditambahkan");
           }
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
        
    }//GEN-LAST:event_submitMouseClicked

    private void textNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNamaKeyPressed
        // TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_BACK_SPACE:
                break;
            case KeyEvent.VK_ENTER:
                textNama.setText(textNama.getText());
                break;
            default:
                EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                String txt = textNama.getText();
                autocomplete(txt);
            }
        });
        }
    }//GEN-LAST:event_textNamaKeyPressed

    private void textNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNamaActionPerformed

    private void CBtanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBtanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBtanggalActionPerformed

    private void CBbulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBbulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBbulanActionPerformed

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        new FormHome().setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonMouseClicked

    private void backButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseEntered
        // TODO add your handling code here:
         ImageIcon A = new ImageIcon(getClass().getResource("icon/backho.png"));
        backButton.setIcon(A);
    }//GEN-LAST:event_backButtonMouseEntered

    private void backButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseExited
        // TODO add your handling code here:
        ImageIcon A = new ImageIcon(getClass().getResource("icon/back.png"));
        backButton.setIcon(A);
    }//GEN-LAST:event_backButtonMouseExited

    private void backButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMousePressed
        // TODO add your handling code here:
        ImageIcon A = new ImageIcon(getClass().getResource("icon/backc.png"));
        backButton.setIcon(A);
    }//GEN-LAST:event_backButtonMousePressed

    private void backButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseReleased
        // TODO add your handling code here:
        ImageIcon A = new ImageIcon(getClass().getResource("icon/back.png"));
        backButton.setIcon(A);
    }//GEN-LAST:event_backButtonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ambil_Minyak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ambil_Minyak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ambil_Minyak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ambil_Minyak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ambil_Minyak().setVisible(true);
            }
        });
    }
    
    private void loadnama(){
        try{
         
            String sql1 = "SELECT * FROM nelayan";
            ResultSet reset = stat.executeQuery(sql1);
            
                while (reset.next()){
                String nama = reset.getString("nama");
                
                nama_nelayan.add(nama);
            
            }
            
          
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    public void autocomplete(String txt){
        String Complete="";
        int start = txt.length();
        int last = txt.length();
        int a;
        
        for(a=0;a<nama_nelayan.size();a++){
            if(nama_nelayan.get(a).toString().startsWith(txt)){
                Complete = nama_nelayan.get(a).toString();
                last = Complete.length();
                break;
            }
        }
        if(last>start) {
            textNama.setText(Complete);
            textNama.setCaretPosition(last);
            textNama.moveCaretPosition(start);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBbulan;
    private javax.swing.JComboBox CBtanggal;
    private javax.swing.JLabel backButton;
    private javax.swing.JLabel background;
    private javax.swing.JButton submit;
    private javax.swing.JTextField textJumlahMinyak;
    private javax.swing.JTextField textNama;
    // End of variables declaration//GEN-END:variables

    private void check() {          
        try{
                String sql1 = "SELECT * FROM nelayan WHERE nama='"+textNama.getText()+"'";
                ResultSet result = stat2.executeQuery(sql1);
                if(result.next() == false){
                    String insert_nama = "INSERT INTO nelayan (nama) VALUES ('"+textNama.getText()+"')";
                    stat3.executeUpdate(insert_nama);
                }
//                    while (result.next()){
//                        String n_nelayan = result.getString("nama");
//                        
//                        checknama(n_nelayan);
//                       
//                    }
                
            } catch(Exception e){
                System.out.println(e.getMessage());
            }
    }


}
