/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pm;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Admin
 */
public class FormHome extends javax.swing.JFrame {

    /**
     * Creates new form FormHome
     */
    int dragxmouse;
    int dragymouse;
    public FormHome() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Close = new javax.swing.JLabel();
        StockOut = new javax.swing.JLabel();
        StockIn = new javax.swing.JLabel();
        Report = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        mouse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("frame0"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(680, 566));
        setResizable(false);
        setSize(new java.awt.Dimension(680, 566));
        getContentPane().setLayout(null);

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/icon/close.png"))); // NOI18N
        Close.setText("jLabel1");
        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CloseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CloseMouseReleased(evt);
            }
        });
        getContentPane().add(Close);
        Close.setBounds(620, 10, 40, 40);

        StockOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/icon/buttonStockOut.png"))); // NOI18N
        StockOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StockOutMouseClicked(evt);
            }
        });
        getContentPane().add(StockOut);
        StockOut.setBounds(360, 170, 218, 124);

        StockIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/icon/buttonStockIn.png"))); // NOI18N
        getContentPane().add(StockIn);
        StockIn.setBounds(360, 240, 218, 124);

        Report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/icon/buttonReport.png"))); // NOI18N
        getContentPane().add(Report);
        Report.setBounds(360, 310, 218, 124);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pm/images/home.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 680, 560);

        mouse.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                mouseMouseDragged(evt);
            }
        });
        mouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mouseMousePressed(evt);
            }
        });
        getContentPane().add(mouse);
        mouse.setBounds(4, 0, 660, 520);

        setSize(new java.awt.Dimension(680, 566));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mouseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseMousePressed
        // TODO add your handling code here:
        dragxmouse = evt.getX();
        dragymouse = evt.getY();
    }//GEN-LAST:event_mouseMousePressed

    private void mouseMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseMouseDragged
        // TODO add your handling code here:
         int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - dragxmouse,y-dragymouse);
        System.out.println(x+","+y);
    }//GEN-LAST:event_mouseMouseDragged

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CloseMouseClicked

    private void CloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseEntered
        // TODO add your handling code here:
        ImageIcon A = new ImageIcon(getClass().getResource("icon/closeho.png"));
        Close.setIcon(A);
    }//GEN-LAST:event_CloseMouseEntered

    private void CloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseExited
        // TODO add your handling code here:
        ImageIcon A = new ImageIcon (getClass().getResource("icon/close.png"));
        Close.setIcon(A);
    }//GEN-LAST:event_CloseMouseExited

    private void CloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMousePressed
        // TODO add your handling code here:
        ImageIcon A = new ImageIcon (getClass().getResource("icon/closec.png"));
        Close.setIcon(A);
    }//GEN-LAST:event_CloseMousePressed

    private void CloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseReleased
        // TODO add your handling code here:
        ImageIcon A = new ImageIcon (getClass().getResource("icon/close.png"));
        Close.setIcon(A);
    }//GEN-LAST:event_CloseMouseReleased

    private void StockOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StockOutMouseClicked
        // TODO add your handling code here:
        new Ambil_Minyak().setVisible(true);
        dispose();
    }//GEN-LAST:event_StockOutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel Report;
    private javax.swing.JLabel StockIn;
    private javax.swing.JLabel StockOut;
    private javax.swing.JLabel mouse;
    // End of variables declaration//GEN-END:variables
}
