/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pm;

import java.awt.EventQueue;
import java.awt.event.KeyEvent;
import java.io.PrintStream;
import java.net.URL;
import java.net.URLConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HITAM-PC
 */
public class home extends javax.swing.JFrame {
    Connection con;
    Statement stat, stat2, stat3, stat4, stat5, stat6, stat7, stat8, stat9, stat10, stat11;
    ResultSet rs;
    String sql;
    ArrayList nama_nelayan = new ArrayList();
    ArrayList nik_nelayan = new ArrayList();
    String harga_beli, harga_jual;
    /**
     * Creates new form home
     */
    public home() {
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
        stat2 = DB.stm;
        stat3 = DB.stm;
        stat4 = DB.stm;
        stat5 = DB.stm;
        stat6 = DB.stm;
        stat7 = DB.stm;
        stat8 = DB.stm;
        stat9 = DB.stm;
        stat10 = DB.stm;
        stat11 = DB.stm;
        
        loadHarga();
        loadnama();
        
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Tanggal = new javax.swing.JLabel();
        textNama = new javax.swing.JTextField();
        textJumlahMinyak = new javax.swing.JTextField();
        CBtanggal = new javax.swing.JComboBox();
        CBbulan = new javax.swing.JComboBox<String>();
        submitAM = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        textNIK = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Tanggal1 = new javax.swing.JLabel();
        textJumlahMinyak1 = new javax.swing.JTextField();
        CBtanggal1 = new javax.swing.JComboBox();
        CBbulan1 = new javax.swing.JComboBox<String>();
        submitSTOCK = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        Sync = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        textHargaBeli = new javax.swing.JTextField();
        textHargaJual = new javax.swing.JTextField();
        submitHarga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bernard MT Condensed", 0, 11)); // NOI18N
        jLabel3.setText("AMBIL MINYAK");

        jLabel1.setText("Nama");

        jLabel2.setText("Jumlah Minyak");

        Tanggal.setText("Tanggal");

        textNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNamaActionPerformed(evt);
            }
        });
        textNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textNamaKeyPressed(evt);
            }
        });

        textJumlahMinyak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textJumlahMinyakActionPerformed(evt);
            }
        });

        CBtanggal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih Tanggal-", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        CBtanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBtanggalActionPerformed(evt);
            }
        });

        CBbulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih Bulan-", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        CBbulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBbulanActionPerformed(evt);
            }
        });

        submitAM.setText("Submit");
        submitAM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitAMMouseClicked(evt);
            }
        });
        submitAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAMActionPerformed(evt);
            }
        });

        jLabel4.setText("NIK");

        textNIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNIKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submitAM))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(Tanggal)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textNama)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CBtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CBbulan, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textJumlahMinyak)
                            .addComponent(textNIK))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textJumlahMinyak)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tanggal)
                    .addComponent(CBtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBbulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitAM)
                .addGap(25, 25, 25))
        );

        jLabel5.setFont(new java.awt.Font("Bernard MT Condensed", 0, 11)); // NOI18N
        jLabel5.setText("STOCK IN");

        jLabel6.setText("Jumlah Minyak");

        Tanggal1.setText("Tanggal");

        textJumlahMinyak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textJumlahMinyak1ActionPerformed(evt);
            }
        });

        CBtanggal1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Pilih Tanggal -", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        CBtanggal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBtanggal1ActionPerformed(evt);
            }
        });

        CBbulan1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Pilih Bulan -", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        CBbulan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBbulan1ActionPerformed(evt);
            }
        });

        submitSTOCK.setText("Submit");
        submitSTOCK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitSTOCKMouseClicked(evt);
            }
        });
        submitSTOCK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitSTOCKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(submitSTOCK)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(Tanggal1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(CBtanggal1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CBbulan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(textJumlahMinyak1))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textJumlahMinyak1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tanggal1)
                    .addComponent(CBtanggal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBbulan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitSTOCK)
                .addGap(49, 49, 49))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setFont(new java.awt.Font("Bernard MT Condensed", 0, 11)); // NOI18N
        jLabel7.setText("Report");

        Sync.setLabel("Sync");
        Sync.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SyncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Sync)
                .addGap(119, 119, 119))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Sync)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Bernard MT Condensed", 0, 12)); // NOI18N
        jLabel8.setText("Harga");

        jLabel9.setText("Harga Beli");

        jLabel10.setText("Harga Jual");

        textHargaBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textHargaBeliActionPerformed(evt);
            }
        });

        submitHarga.setText("Submit");
        submitHarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitHargaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(submitHarga)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addGap(25, 25, 25)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textHargaBeli)
                                .addComponent(textHargaJual, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(textHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitHarga)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textJumlahMinyakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textJumlahMinyakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textJumlahMinyakActionPerformed

    private void submitAMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitAMMouseClicked
        String nama = textNama.getText();
        String jumlah_minyak = textJumlahMinyak.getText();
        String no_nik = textNIK.getText();
        
        SimpleDateFormat sdf = new SimpleDateFormat();
        int numbers_to_add_max = 31;
        for (int i = 1; i <= numbers_to_add_max; i++) {
            CBtanggal.addItem(new Integer(i));
        }
        int year = Calendar.getInstance().get(Calendar.YEAR);
        
        String tanggal = CBtanggal.getSelectedItem().toString();
        String bulan = CBbulan.getSelectedItem().toString();
        String dmy = year+"-"+bulan+"-"+tanggal;
        check();
        try{
           if(nama.isEmpty() || no_nik.isEmpty() || jumlah_minyak.isEmpty() || tanggal.isEmpty() || bulan.isEmpty()){
               JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!!!");
           }else{
//                check_minyak();
                String total_minyak_in = "select (select sum(jumlah) from stock_in where status='in') as jumlah_in, "
                        + "(select sum(jumlah) from stock_in where status='out') as jumlah_out";
                ResultSet total = stat5.executeQuery(total_minyak_in);
                if(total.next() ){
                    String jumlah_in = total.getString("jumlah_in");
                    String jumlah_out = total.getString("jumlah_out");
                    float jumlah = 0;
                    System.out.println(jumlah_in);
                    System.out.println(jumlah_out);
                    if(jumlah_out == null){
                        jumlah = Float.parseFloat(jumlah_in);
//                        JOptionPane.showMessageDialog(null, "jumlah : "+jumlah);
//                        System.out.println("null :"+jumlah);
                    } 
                    else{
                        jumlah = Float.parseFloat(jumlah_in) - Float.parseFloat(jumlah_out);
                    }
                    if(jumlah < Integer.parseInt(jumlah_minyak)){
                        JOptionPane.showMessageDialog(null, "Stock minyak kurang!!!, "
                                + "Silahkan tambah stock minyak terlebih dahulu");
                    } else{
                        String insert_minyak = "INSERT INTO ambil_minyak (nama_nelayan, nik, tanggal, jumlah) "
                        + "VALUES ('"+nama+"','"+no_nik+"','"+String.valueOf(dmy)+"','"+jumlah_minyak+"')";
                        stat4.executeUpdate(insert_minyak); 
                        JOptionPane.showMessageDialog(null, "Data Berhasil ditambahkan");
                    }
//                    JOptionPane.showConfirmDialog(null, "Total : "+jumlah);
                  
                }

           }
           
        }catch(Exception e){
//            JOptionPane.showMessageDialog(this, e.getMessage());
            System.out.println(e.getMessage());
        }
        
        
    }//GEN-LAST:event_submitAMMouseClicked

    private void textNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textNamaKeyPressed
        // TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_BACK_SPACE:
                break;
            case KeyEvent.VK_ENTER:
                textNama.setText(textNama.getText());
                break;
            default:
                EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                String txt = textNama.getText();
                autocomplete(txt);
            }
        });
        }
    }//GEN-LAST:event_textNamaKeyPressed

    private void textNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNamaActionPerformed

    private void CBtanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBtanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBtanggalActionPerformed

    private void CBbulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBbulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBbulanActionPerformed

    private void submitAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitAMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitAMActionPerformed

    private void textNIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNIKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNIKActionPerformed

    private void textJumlahMinyak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textJumlahMinyak1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textJumlahMinyak1ActionPerformed

    private void CBtanggal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBtanggal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBtanggal1ActionPerformed

    private void CBbulan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBbulan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBbulan1ActionPerformed
    
    private void submitSTOCKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitSTOCKMouseClicked
        String jumlah_minyak = textJumlahMinyak.getText();

        SimpleDateFormat sdf = new SimpleDateFormat();
        int numbers_to_add_max = 31;
        for (int i = 1; i <= numbers_to_add_max; i++) {
            CBtanggal.addItem(new Integer(i));
        }
        int year = Calendar.getInstance().get(Calendar.YEAR);

        String tanggal = CBtanggal.getSelectedItem().toString();
        String bulan = CBbulan.getSelectedItem().toString();
        String dmy = year+"-"+bulan+"-"+tanggal;

        try{
            if(jumlah_minyak.isEmpty() || tanggal.isEmpty() || bulan.isEmpty()){
                JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!!!");
            }else{
                String insert_minyak = "INSERT INTO stock_in ( tanggal, jumlah, status) "
                + "VALUES ('"+String.valueOf(dmy)+"','"+jumlah_minyak+"', 'in')";
                stat4.executeUpdate(insert_minyak);
                JOptionPane.showMessageDialog(null, "Data Berhasil ditambahkan");
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_submitSTOCKMouseClicked

    private void submitSTOCKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitSTOCKActionPerformed
        String jumlah_minyak = textJumlahMinyak1.getText();

        SimpleDateFormat sdf = new SimpleDateFormat();
        int numbers_to_add_max = 31;
        for (int i = 1; i <= numbers_to_add_max; i++) {
            CBtanggal1.addItem(new Integer(i));
        }
        int year = Calendar.getInstance().get(Calendar.YEAR);

        String tanggal = CBtanggal1.getSelectedItem().toString();
        String bulan = CBbulan1.getSelectedItem().toString();
        String dmy = year+"-"+bulan+"-"+tanggal;
        
        try{
            if(jumlah_minyak.isEmpty() || tanggal.isEmpty() || bulan.isEmpty()){
                JOptionPane.showMessageDialog(null, "Data tidak boleh kosong!!!");
            }else{
                String insert_minyak = "INSERT INTO stock_in ( tanggal, jumlah, status) "
                + "VALUES ('"+String.valueOf(dmy)+"','"+jumlah_minyak+"', 'in')";
                stat4.executeUpdate(insert_minyak);
                JOptionPane.showMessageDialog(null, "Data Berhasil ditambahkan");
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_submitSTOCKActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        textHargaBeli.setText(harga_beli);
        textHargaJual.setText(harga_jual);
        
        DefaultTableModel model = new DefaultTableModel(new String[]{"No", "NIK", "Nama Nelayan", "Tanggal","Jumlah"}, 0);
        try{
          String sql = "SELECT * FROM ambil_minyak ORDER BY tanggal desc";
          ResultSet rs = stat6.executeQuery(sql);
          int no = 0;
          while(rs.next()){
              String nama = rs.getString("nama_nelayan");
              String tanggal = rs.getString("tanggal");
              String jumlah = rs.getString("jumlah");
              String nik = rs.getString("nik");
              String id = rs.getString("id");
              no = no + 1;
//              int rows = jTable1.getColumnCount();
//              for(int i=1;i<=rows;i++){
//                
//              }
              model.addRow(new Object[]{no, nik, nama, tanggal, jumlah});
              jTable1.setModel(model);
              
//              String id = rs.getString("id");
              
              

          }
        }catch(Exception e){
          JOptionPane.showMessageDialog(this, "Error : "+e.getMessage());
      }
    }//GEN-LAST:event_formWindowActivated

    private void textHargaBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHargaBeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textHargaBeliActionPerformed

    private void submitHargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitHargaMouseClicked
        String hargaBeli = textHargaBeli.getText();
        String hargaJual = textHargaJual.getText();
        try{
            String updateHarga = "UPDATE harga SET harga_beli='"+hargaBeli+"', harga_jual='"+hargaJual+"'"
                    + " WHERE id=1";
            stat10.executeUpdate(updateHarga);
            JOptionPane.showMessageDialog(null, "Berhasil mengubah harga");
            loadHarga();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error : "+e.getMessage());
        }
    }//GEN-LAST:event_submitHargaMouseClicked

    private void SyncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SyncActionPerformed
        try{
             String sql = "SELECT * FROM ambil_minyak";
          ResultSet rs = stat6.executeQuery(sql);
          
          while(rs.next()){
              String nama = rs.getString("nama_nelayan");
              String tanggal = rs.getString("tanggal");
              String jumlah = rs.getString("jumlah");
              String id = rs.getString("id");
          
            URL url = new URL("https://lintasjakartabunguran.com/pm/insertlocal.php");
            URLConnection con = url.openConnection();
            // activate the output
            con.setDoOutput(true);
            PrintStream ps = new PrintStream(con.getOutputStream());
            // send your parameters to your site
            ps.print("&nama_nelayan="+nama);
            ps.print("&tanggal="+tanggal);               
            ps.print("jumlah="+jumlah);

            // we have to get the input stream in order to actually send the request
            con.getInputStream();
            System.out.println("OK");
            // close the print stream
            ps.close();
          }
          }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_SyncActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }
    
    private void loadnama(){
        try{
         
            String sql1 = "SELECT * FROM nelayan";
            ResultSet reset = stat.executeQuery(sql1);
            
                while (reset.next()){
                String nama = reset.getString("nama");
//                String nik = reset.getString("nik");
                
                nama_nelayan.add(nama);
            }
            
          
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    public void autocomplete(String txt){
        String Complete="";
        int start = txt.length();
        int last = txt.length();
        int a;
        
        for(a=0;a<nama_nelayan.size();a++){
            if(nama_nelayan.get(a).toString().startsWith(txt)){
                Complete = nama_nelayan.get(a).toString();
                last = Complete.length();
                break;
            }
        }
        if(last>start) {
            textNama.setText(Complete);
            textNama.setCaretPosition(last);
            textNama.moveCaretPosition(start);
            
            
        }
        try{
            String sqlnik = "SELECT nik FROM nelayan WHERE nama='"+textNama.getText()+"'";
            ResultSet resus = stat7.executeQuery(sqlnik); 
            if(resus.next()){
               textNIK.setText(resus.getString("nik"));
            } else {
               textNIK.setText("");

            }
            }catch(Exception e){
                System.out.println("KOCONG");
        }
//        if(textNama.getText().isEmpty()){
//        }
        

        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBbulan;
    private javax.swing.JComboBox<String> CBbulan1;
    private javax.swing.JComboBox CBtanggal;
    private javax.swing.JComboBox CBtanggal1;
    private javax.swing.JButton Sync;
    private javax.swing.JLabel Tanggal;
    private javax.swing.JLabel Tanggal1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton submitAM;
    private javax.swing.JButton submitHarga;
    private javax.swing.JButton submitSTOCK;
    private javax.swing.JTextField textHargaBeli;
    private javax.swing.JTextField textHargaJual;
    private javax.swing.JTextField textJumlahMinyak;
    private javax.swing.JTextField textJumlahMinyak1;
    private javax.swing.JTextField textNIK;
    private javax.swing.JTextField textNama;
    // End of variables declaration//GEN-END:variables

    private void check() {          
        try{
                String sql1 = "SELECT * FROM nelayan WHERE nama='"+textNama.getText()+"'";
                ResultSet result = stat2.executeQuery(sql1);
                if(result.next() == false){
                    String insert_nama = "INSERT INTO nelayan (nama, nik) VALUES ('"+textNama.getText()+"', '"+textNIK.getText()+"')";
                    stat3.executeUpdate(insert_nama);
                }
//                    while (result.next()){
//                        String n_nelayan = result.getString("nama");
//                        
//                        checknama(n_nelayan);
//                       
//                    }
                
            } catch(Exception e){
                System.out.println(e.getMessage());
            }
    }

    private void check_minyak() {
        try{
            String status_minyak = "SELECT status FROM stock_in";
            ResultSet srt = stat8.executeQuery(status_minyak);
                while(srt.next()){
                    String status = srt.getString("status");
                    if(!status.equals("out")){
                        String sqlin = "select sum(jumlah) from stock_in where status='in'";
                    }
                }
        } catch(Exception e){
            
        }
        
    }

    private void loadHarga() {
        try{
            String hargaMinyak = "SELECT * FROM harga WHERE id=1";
            ResultSet sete = stat9.executeQuery(hargaMinyak);
                if(sete.next() == true){
                    harga_beli = sete.getString("harga_beli");
                    harga_jual = sete.getString("harga_jual");
                    
//                    textHargaBeli.setText(String.valueOf(harga_beli));
//                    textHargaJual.setText(String.valueOf(harga_jual));
                } 
                
        }catch(Exception e){
            System.out.println("ERROR: "+e.getMessage());
        }
    }


}
